version: 2

sources:
  - name: staging
    database:
      eminent-tape-413010
      # For postgres:
      #database: production
    schema:
      trips_data_all

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_taxidata
      - name:
          yellow_taxidata
          # freshness:
          # error_after: {count: 6, period: hour}
